// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwonpyseewpswmuktglm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3b25weXNlZXdwc3dtdWt0Z2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDYwNDAsImV4cCI6MjA3NTY4MjA0MH0.HO1A_DkjisMIgYl8s0YDAC-d7ZPTt8jQvWJlMmkGWto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});